-- =====================================================================
--  MicroBank Manager - Script de creation de la base de donnees
--  SGBD : PostgreSQL 13 ou superieur
--
--  Utilisation :
--      createdb microbank
--      psql -d microbank -f database.sql
--
--  Le schema correspond exactement aux entites JPA de l'application
--  (il a ete genere a partir du mapping Hibernate, puis commente).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Nettoyage : permet de rejouer le script sur une base existante.
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS operations CASCADE;
DROP TABLE IF EXISTS client_documents CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS agencies CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ---------------------------------------------------------------------
-- 2. Utilisateurs de l'application (agents et administrateurs)
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom           VARCHAR(100) NOT NULL,
    prenom        VARCHAR(100) NOT NULL,
    login         VARCHAR(50)  NOT NULL UNIQUE,
    -- Empreinte PBKDF2, jamais le mot de passe en clair.
    mot_de_passe  VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL CHECK (role IN ('AGENT', 'ADMIN')),
    statut        VARCHAR(20)  NOT NULL CHECK (statut IN ('ACTIF', 'INACTIF')),
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6)
);

-- ---------------------------------------------------------------------
-- 3. Agences (bonus 4)
-- ---------------------------------------------------------------------
CREATE TABLE agencies (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(20)  NOT NULL UNIQUE,
    nom        VARCHAR(100) NOT NULL,
    ville      VARCHAR(100) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);

-- ---------------------------------------------------------------------
-- 4. Clients
-- ---------------------------------------------------------------------
CREATE TABLE clients (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom            VARCHAR(100) NOT NULL,
    prenom         VARCHAR(100) NOT NULL,
    date_naissance DATE,
    telephone      VARCHAR(30)  NOT NULL,
    email          VARCHAR(150),
    adresse        VARCHAR(255),
    numero_piece   VARCHAR(50)  NOT NULL UNIQUE,
    date_creation  DATE         NOT NULL,
    statut         VARCHAR(20)  NOT NULL CHECK (statut IN ('ACTIF', 'INACTIF')),
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6)
);

-- Accelere la recherche de clients par nom, prenom ou telephone (§9).
CREATE INDEX idx_clients_nom ON clients (LOWER(nom));
CREATE INDEX idx_clients_prenom ON clients (LOWER(prenom));
CREATE INDEX idx_clients_telephone ON clients (telephone);

-- ---------------------------------------------------------------------
-- 5. Piece d'identite numerisee : relation Client 1 --- 1 ClientDocument
-- ---------------------------------------------------------------------
CREATE TABLE client_documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT       NOT NULL UNIQUE,
    nom_fichier   VARCHAR(255) NOT NULL,
    type_contenu  VARCHAR(100) NOT NULL,
    taille_octets BIGINT       NOT NULL,
    contenu       BYTEA        NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6),
    CONSTRAINT fk_client_documents_client
        FOREIGN KEY (client_id) REFERENCES clients (id)
);

-- ---------------------------------------------------------------------
-- 6. Comptes : relation Client 1 --- * Account
-- ---------------------------------------------------------------------
CREATE TABLE accounts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_compte     VARCHAR(20)    NOT NULL UNIQUE,
    type              VARCHAR(20)    NOT NULL CHECK (type IN ('COURANT', 'EPARGNE')),
    solde             NUMERIC(15, 2) NOT NULL,
    date_ouverture    DATE           NOT NULL,
    statut            VARCHAR(20)    NOT NULL
                      CHECK (statut IN ('ACTIF', 'BLOQUE', 'CLOTURE')),
    client_id         BIGINT         NOT NULL,
    agency_id         BIGINT,
    -- Verrou optimiste : empeche deux operations simultanees d'ecraser le solde.
    version_optimiste BIGINT         NOT NULL DEFAULT 0,
    created_at        TIMESTAMP(6)   NOT NULL,
    updated_at        TIMESTAMP(6),
    CONSTRAINT fk_accounts_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_accounts_agency FOREIGN KEY (agency_id) REFERENCES agencies (id)
);

CREATE INDEX idx_accounts_client ON accounts (client_id);

-- ---------------------------------------------------------------------
-- 7. Operations : relations Account 1 --- * Operation et User 1 --- * Operation
--    Un virement produit deux lignes partageant la meme reference :
--    un DEBIT sur le compte source, un CREDIT sur le compte destination.
-- ---------------------------------------------------------------------
CREATE TABLE operations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference           VARCHAR(30)    NOT NULL,
    type                VARCHAR(20)    NOT NULL
                        CHECK (type IN ('DEPOT', 'RETRAIT', 'VIREMENT')),
    sens                VARCHAR(10)    NOT NULL CHECK (sens IN ('CREDIT', 'DEBIT')),
    montant             NUMERIC(15, 2) NOT NULL CHECK (montant > 0),
    solde_apres         NUMERIC(15, 2) NOT NULL,
    date_operation      TIMESTAMP(6)   NOT NULL,
    description         VARCHAR(255),
    compte_contrepartie VARCHAR(20),
    account_id          BIGINT         NOT NULL,
    user_id             BIGINT         NOT NULL,
    created_at          TIMESTAMP(6)   NOT NULL,
    updated_at          TIMESTAMP(6),
    CONSTRAINT fk_operations_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT fk_operations_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Historique filtre et pagine (§17 a §19) : tri par date sur un compte donne.
CREATE INDEX idx_operations_compte_date ON operations (account_id, date_operation DESC);
CREATE INDEX idx_operations_date ON operations (date_operation);
CREATE INDEX idx_operations_type ON operations (type);

-- =====================================================================
--  JEU DE DONNEES DE DEPART
-- =====================================================================

-- Comptes de test.
--   admin / admin123 : administrateur (gestion des utilisateurs incluse)
--   agent / agent123 : agent
-- Les valeurs ci-dessous sont des empreintes PBKDF2-HMAC-SHA256 (120 000 iterations).
INSERT INTO users (nom, prenom, login, mot_de_passe, role, statut, created_at, updated_at)
VALUES
    ('GAYE', 'Abdoulaye', 'admin',
     'pbkdf2_sha256$120000$Zlh1sx6FXphIJ3tBI5wwog==$GEOFRgtKiJLWOILPlOMSBw7RLPtmz6v38Fmg8RJ/cOE=',
     'ADMIN', 'ACTIF', NOW(), NOW()),
    ('DIOP', 'Awa', 'agent',
     'pbkdf2_sha256$120000$7ybd260CplEwJg/b35s0tw==$HkIAZxes8v8pbKqi0JLRM28B+bufmG5jfdcwY1A7lks=',
     'AGENT', 'ACTIF', NOW(), NOW());

INSERT INTO agencies (code, nom, ville, created_at, updated_at)
VALUES
    ('AG-DKR', 'Agence de Dakar', 'Dakar', NOW(), NOW()),
    ('AG-THS', 'Agence de Thies', 'Thies', NOW(), NOW());

INSERT INTO clients (nom, prenom, date_naissance, telephone, email, adresse,
                     numero_piece, date_creation, statut, created_at, updated_at)
VALUES
    ('GAYE', 'Abdoulaye', DATE '1988-03-12', '77 123 45 67', 'abdoulaye.gaye@example.com',
     'Dakar, Plateau', 'CNI-1988-0312', CURRENT_DATE, 'ACTIF', NOW(), NOW()),
    ('DIOP', 'Awa', DATE '1992-07-25', '76 987 65 43', 'awa.diop@example.com',
     'Dakar, Medina', 'CNI-1992-0725', CURRENT_DATE, 'ACTIF', NOW(), NOW()),
    ('SOW', 'Fatou', DATE '1995-11-02', '78 555 22 11', 'fatou.sow@example.com',
     'Thies, Centre', 'CNI-1995-1102', CURRENT_DATE, 'ACTIF', NOW(), NOW());

INSERT INTO accounts (numero_compte, type, solde, date_ouverture, statut,
                      client_id, agency_id, version_optimiste, created_at, updated_at)
VALUES
    ('100001', 'COURANT', 100000.00, CURRENT_DATE, 'ACTIF', 1, 1, 0, NOW(), NOW()),
    ('100002', 'EPARGNE',  50000.00, CURRENT_DATE, 'ACTIF', 2, 1, 0, NOW(), NOW()),
    ('100003', 'COURANT',      0.00, CURRENT_DATE, 'ACTIF', 3, 2, 0, NOW(), NOW());

INSERT INTO operations (reference, type, sens, montant, solde_apres, date_operation,
                        description, compte_contrepartie, account_id, user_id,
                        created_at, updated_at)
VALUES
    ('OP' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || '-000001', 'DEPOT', 'CREDIT',
     100000.00, 100000.00, NOW(), 'Depot initial a l''ouverture du compte',
     NULL, 1, 1, NOW(), NOW()),
    ('OP' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || '-000002', 'DEPOT', 'CREDIT',
     50000.00, 50000.00, NOW(), 'Depot initial a l''ouverture du compte',
     NULL, 2, 1, NOW(), NOW());

-- =====================================================================
--  Verification rapide
-- =====================================================================
-- SELECT COUNT(*) FROM users;      -- 2
-- SELECT COUNT(*) FROM clients;    -- 3
-- SELECT COUNT(*) FROM accounts;   -- 3
-- SELECT COUNT(*) FROM operations; -- 2
